project:
  title: "revealjs_template"

editor: visual


author:
  - name: Janick Weberpals, RPh, PhD
    corresponding: true
    orcid: 0000-0003-0404-7394
    email: jweberpals@bwh.harvard.edu
    url: janickweberpals.github.io
    affiliations:
      - name: Division of Pharmacoepidemiology and Pharmacoeconomics <br> Brigham and Women's Hospital <br> Harvard Medical School
        address: 1620 Tremont Street
        city: Boston
        state: MA
        postal-code: 02120